### ISSUE TITLE
Add Minio as a basic dependency. Use by default unless another S3 endpoint is provided.

### ISSUE THREAD

**Issue by AVSuni** [silogen/kaiwo#88]
We should probably just go with supporting the S3 API endpoint within Kaiwo without making any assumptions which implementation it is. For the reference stack we should use Minio.

- [ ] Uploading workload files
  * Any file from the workload path (not just text files now) that is not on the exclude list can be uploaded to an existing bucket.
  * If files exist in the given path, the user is asked to confirm if they would like to overwrite them.
  * ConfigMap storage is still available, but cannot store large or binary files. If large / binary files are encountered while using config map storage, the user is prompted to confirm if they want to continue without them or cancel
  * If the storage type is not specified, a secret with the name `kaiwo-workload-s3` is searched for in the current namespace, which includes
    * The endpoint `endpoint`
    * The access ID key `accessId`
    * The secret key `secretKey`
  * If the secret is found, S3 storage is used, otherwise ConfigMap storage is used
  * By default the bucket used is `namespace/username/workloadType/workloadName`, but this can be overridden via `--workload-s3-bucket=bucketName`
  * The s3 endpoint and secret **references** can be provided via the CLI as well `--workload-s3-endpoint`, `--workload-s3-secret=secretName`, `--workload-s3-access-id-secret-ref=key for access id` and `--workload-s3-access-key-secret-ref=key for secret key `

- [ ] Specifying other S3 data
  * The user can list additional data they want to make available to the container via a config file with a syntax similar to the one below

- [ ] Init containers are added to each workload, which ensure that data from the bucket (and any other buckets that were specified) is downloaded before the main workload starts
  * The user-provided and kaiwo-workload requests are combined
  * Secrets are created as environmental variables
  * The default Minio image is used with a command that downloads each requested path sequentually

It is the user's responsibility to ensure that the download paths point to the PVC storage mount `/workload`.

```yaml
initContainerDownloads:
  - bucket:
        endpoint: ...
        credentials:
            secret: <secret name>
            accessKeyIdRef: ...
            secretKeyRef: ...
        paths:
            - source: /  # Relative to endpoint
              destination: /workload/config  # Mount path in container
```

The `source` may point to a bucket, a path within a bucket, or a single object within a bucket.

This config file can be stored in the workload path and will be picked up automatically.

The secrets used to access the buckets must exist within the cluster and the given namespace, the Kaiwo CLI will not manage them.
